// This file is auto-generated by Lovable. Do not modify it.

// Auth OAuth is not supported in localStorage mode.
export const lovable = {
  auth: {
    signInWithOAuth: async () => ({ error: new Error("Authentification OAuth non supportée en mode local") }),
  },
};
