ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS pay_name TEXT,
  ADD COLUMN IF NOT EXISTS pay_phone TEXT,
  ADD COLUMN IF NOT EXISTS pay_operator TEXT;
